### ISSUE TITLE
Whats that

### ISSUE THREAD

**Issue by TheBjoRedCraft** [LucasHenriqueDG/SurfPranks#1]
How do i use the plugin?

**Comment by TheBjoRedCraft** [comment]
Do you have discord?

**Comment by LucasHenriqueDG** [comment]
my discord is https://discord.com/invite/awNnacmnds

**Comment by LucasHenriqueDG** [comment]
> How do i use the plugin?

currently the plugin has one command, that is /prank fart

**Comment by TheBjoRedCraft** [comment]
ok thanks
